### ISSUE TITLE
Add a license please

### ISSUE THREAD

**Issue by nerdachse** [jacopograndi/voxel-experiment#1]
Hello!

Thanks for sharing your work with the world!

I am working on something similar, yet a bit distinct (interested in smaller voxels than minecraft) and stumbled upon your repository. Mine is already multiplayer (bevy_quinnet), server authorative but I am not happy with it and am in the process of rewriting to using a compute shader raytracing approach instead of CPU meshing.

Would you be so kind and add a license file so one can make a more informed guess about what is allowed to be cannibalized ;), or rather how far inspiration goes and how contributions are licensed.

Would you be so kind and add one? Thanks a bunch for considering!

And if it's this time of the year for you: Merry Christmas and a Happy New Year!

**Comment by jacopograndi** [comment]
Hello! I wasn't expecting anyone to notice this repo. I took a lot of inspiration from [bevy-voxel-engine](https://github.com/ria8651/bevy-voxel-engine). Given it's licensed with a dual MIT-Apache license i think for this repo is fair to do that as well.

**Comment by jacopograndi** [comment]
ps: Happy festivities to you as well!
