### ISSUE TITLE
BlockInfo

### ISSUE THREAD

**Issue by jacopograndi** [jacopograndi/voxel-experiment#11]
We need a way to logically store the properties of a block, like a block blueprint library. I was thinking that they could be loaded from a file and stored in ram as a HashMap<String, BlockInfo>, with String being the name of the block so that we can say something like universe.set_at(pos, BlockInfos.get("Stone").unwrap())
```
struct BlockInfo {
   name: String,
   opaque: bool,
   collidable: bool,
   light_level: u8,
   voxel_texture_path: String,
   drop_item_id: String,
   ...
}
```
Maybe we give unique ids to each logical block instead of going by name?

**Comment by magiwanders** [comment]
Basic blockinfo implemented. Now all default are stored in assets>blockinfo.ron. A RON crate abstraction layer is in voxel_info crate. A static BLOCK_INFO is created at runtime, which is used by Block::new uses.

Consider merging voxel_info into voxel_storage
