### ISSUE TITLE
Texture handling improvement

### ISSUE THREAD

**Issue by magiwanders** [jacopograndi/voxel-experiment#9]
Main grid voxel textures handling
1.  Create some basic voxel models
    - [ ] Dirt
    - [ ] Stone
    - [ ] Wood
     - [ ] Fence
     - [ ] Torch

2. Load the .vox textures from multiple folders
4. Load the BlockInfo data from multiple folders
5. Assign to each BlockInfo a BlockId
6. The voxel.id is the BlockId
 7. Construct the textures buffer
    - Contiguous
    - The first 256 (can be expanded if needed) are 16x16x16 voxels
7. While tracing, use the voxel.id as the offset in the texture buffer

Now i have to cycle each voxel texture box to check if it's a hit for each pixel.
    I should check only the ones that touch current voxel while tracing the main voxel grid.
    Doing so requires a HashMap<IVec3, Vec<TextureOffset>>, which is huge.
    If i restrict the key IVec3 to being only 0..32 values, it would be smaller.
    I could restrict it further if needed, it shouldn't need to be chunk-aligned.

    1. HashMap<IVec3ModuloChunkSide, Vec<TextureOffset>> shader support
        
        - texture_offsets: array<u32>
        - keys: array<TextureOffsets>
        - struct TextureOffset { offset: u32, size: u32 }
        - Index into keys with the current map_pos and cycle size times 

    2. Construct the texture_offsets and keys from the extracted TextureBoxes every frame
    3. Cache the hit for the current pixel if i have large TextureBoxes.
    4. Test with and without optimization

**Comment by jacopograndi** [comment]
This is all implemented.
